# Generated by Django 3.0.3 on 2020-03-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='tea_pics')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.TeaType')),
            ],
        ),
    ]
